# Generated by Django 3.2.6 on 2021-08-16 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='usr',
            new_name='user',
        ),
    ]
